# Generated by Django 5.2.4 on 2025-07-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='batch_size',
            field=models.IntegerField(default=32, help_text='Training batch size'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='epochs',
            field=models.IntegerField(default=50, help_text='Number of training epochs'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='final_epoch',
            field=models.IntegerField(blank=True, help_text='Final epoch completed', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='training_time_seconds',
            field=models.FloatField(blank=True, help_text='Total training time in seconds', null=True),
        ),
    ]
